# permissions for end users to view batches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: batch-viewer-role
rules:
- apiGroups:
  - pancakes.ricfeatherstone.com
  resources:
  - batches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pancakes.ricfeatherstone.com
  resources:
  - batches/status
  verbs:
  - get
